"""Status bar materializers: Waybar (Wayland) and Polybar (X11)."""
import sys

from core.constants import HOME, TEMPLATES_DIR
from core.process import run_cmd
from core.backup import backup_file
from core.templates import render_template


# ---------------------------------------------------------------------------
# Waybar
# ---------------------------------------------------------------------------

def materialize_waybar(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    waybar_dir = HOME / ".config" / "waybar"
    style_path = waybar_dir / "style-hermes.css"
    config_path = waybar_dir / "config"
    changes = []

    content = f"""/* Generated by linux-ricing — {design.get('name', 'theme')} */
* {{
    font-family: "{design.get('typography', {}).get('ui_font', 'Inter')}", sans-serif;
    font-size: 14px;
}}

window#waybar {{
    background-color: {palette['background']};
    color: {palette['foreground']};
    border-bottom: 2px solid {palette['primary']};
}}

#workspaces button {{
    color: {palette['muted']};
    padding: 0 5px;
}}

#workspaces button.focused {{
    background-color: {palette['primary']};
    color: {palette['background']};
}}

#clock, #battery, #network, #pulseaudio {{
    padding: 0 10px;
    color: {palette['foreground']};
}}

#battery.warning {{
    color: {palette['warning']};
}}

#battery.critical {{
    color: {palette['danger']};
}}
"""

    if dry_run:
        changes.append({"app": "waybar", "action": "dry-run", "path": str(style_path)})
        return changes

    waybar_dir.mkdir(parents=True, exist_ok=True)
    style_backup = backup_file(style_path, backup_ts, "waybar/style-hermes.css")
    config_backup = backup_file(config_path, backup_ts, "waybar/config")
    style_path.write_text(content, encoding="utf-8")
    changes.append({"app": "waybar", "action": "write", "path": str(style_path),
                    "backup": style_backup, "config_backup": config_backup, "config_path": str(config_path)})

    main_style = waybar_dir / "style.css"
    import_line = f'@import "{style_path}";'
    hermes_marker = "/* linux-ricing */"
    hermes_marker_end = "/* end-linux-ricing */"
    injected = False
    if main_style.exists():
        css_text = main_style.read_text(encoding="utf-8")
        if hermes_marker not in css_text:
            main_style.write_text(
                f"{hermes_marker}\n{import_line}\n{hermes_marker_end}\n\n" + css_text,
                encoding="utf-8",
            )
            injected = True
    else:
        main_style.write_text(
            f"{hermes_marker}\n{import_line}\n{hermes_marker_end}\n", encoding="utf-8"
        )
        injected = True

    changes.append({"app": "waybar", "action": "inject_include", "path": str(main_style),
                    "injected": injected, "import_line": import_line,
                    "marker": hermes_marker, "marker_end": hermes_marker_end})
    run_cmd(["pkill", "-SIGUSR2", "waybar"], timeout=3)
    return changes


# ---------------------------------------------------------------------------
# Polybar
# ---------------------------------------------------------------------------

def materialize_polybar(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    polybar_dir = HOME / ".config" / "polybar"
    config_path = polybar_dir / "config.ini"
    colors_path = polybar_dir / "hermes-colors.ini"
    template_path = TEMPLATES_DIR / "polybar" / "hermes-colors.ini.template"
    changes = []

    if not template_path.exists():
        print(f"[polybar] template not found, skipping: {template_path}", file=sys.stderr)
        return changes

    context = {**palette, "name": design.get("name", "theme")}
    colors_content = render_template(template_path, context)

    if dry_run:
        changes.append({"app": "polybar", "action": "dry-run", "path": str(colors_path)})
        return changes

    polybar_dir.mkdir(parents=True, exist_ok=True)
    colors_backup = backup_file(colors_path, backup_ts, "polybar/hermes-colors.ini")
    config_backup = backup_file(config_path, backup_ts, "polybar/config.ini")
    colors_path.write_text(colors_content, encoding="utf-8")
    changes.append({"app": "polybar", "action": "write", "path": str(colors_path), "backup": colors_backup})

    hermes_marker = "; linux-ricing"
    hermes_marker_end = "; end-linux-ricing"
    include_line = f"include-file = {colors_path}"
    injected = False
    if config_path.exists():
        config_text = config_path.read_text(encoding="utf-8")
        if "hermes-colors.ini" not in config_text:
            config_path.write_text(
                f"{hermes_marker}\n{include_line}\n{hermes_marker_end}\n\n" + config_text,
                encoding="utf-8",
            )
            injected = True
    else:
        config_path.write_text(
            f"{hermes_marker}\n{include_line}\n{hermes_marker_end}\n\n"
            "; Add your [bar/...] and [module/...] configs below\n",
            encoding="utf-8",
        )
        injected = True

    changes.append({"app": "polybar", "action": "inject_include", "path": str(config_path),
                    "backup": config_backup, "injected": injected,
                    "marker": hermes_marker, "marker_end": hermes_marker_end})
    return changes
