"""Application launcher materializers: Rofi and Wofi."""
import sys

from core.constants import HOME, TEMPLATES_DIR
from core.colors import yiq_text_color
from core.backup import backup_file
from core.templates import render_template


# ---------------------------------------------------------------------------
# Rofi
# ---------------------------------------------------------------------------

def materialize_rofi(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    rofi_dir = HOME / ".config" / "rofi"
    theme_path = rofi_dir / "hermes-theme.rasi"
    config_path = rofi_dir / "config.rasi"
    changes = []

    content = f"""/* Generated by linux-ricing — {design.get('name', 'theme')} */
* {{
    background:   {palette['background']};
    foreground:   {palette['foreground']};
    primary:      {palette['primary']};
    secondary:    {palette['secondary']};
    accent:       {palette['accent']};
    surface:      {palette['surface']};
    muted:        {palette['muted']};
    danger:       {palette['danger']};
    success:      {palette['success']};
    warning:      {palette['warning']};
    transparent:  rgba(0,0,0,0%);
}}

configuration {{
    show-icons: true;
}}

window {{
    background-color: @background;
    border:           2px;
    border-color:     @primary;
    border-radius:    8px;
    padding:          16px;
    width:            40%;
}}

mainbox {{
    background-color: @transparent;
    children:         [ inputbar, message, listview ];
    spacing:          12px;
}}

inputbar {{
    background-color: @surface;
    text-color:       @foreground;
    border-radius:    6px;
    padding:          8px 12px;
    spacing:          8px;
    children:         [ prompt, entry ];
}}

prompt {{
    background-color: @transparent;
    text-color:       @accent;
}}

entry {{
    background-color:  @transparent;
    text-color:        @foreground;
    placeholder:       "Search...";
    placeholder-color: @muted;
    cursor:            text;
}}

message {{
    background-color: @surface;
    text-color:       @foreground;
    border-radius:    6px;
    padding:          8px;
}}

textbox {{
    background-color: @transparent;
    text-color:       @foreground;
}}

listview {{
    background-color: @transparent;
    columns:          1;
    lines:            8;
    spacing:          4px;
    scrollbar:        true;
    fixed-height:     true;
    cycle:            true;
}}

scrollbar {{
    background-color: @surface;
    handle-color:     @accent;
    handle-width:     6px;
    border-radius:    4px;
}}

element {{
    background-color: @transparent;
    text-color:       @foreground;
    padding:          6px 10px;
    border-radius:    4px;
    spacing:          8px;
}}

element normal.normal {{ text-color: @foreground; }}
element normal.urgent {{ text-color: @danger; }}
element normal.active {{ text-color: @success; }}

element selected.normal {{
    background-color: @primary;
    text-color:       @background;
}}
element selected.urgent {{
    background-color: @danger;
    text-color:       @background;
}}
element selected.active {{
    background-color: @success;
    text-color:       @background;
}}

element-icon {{
    background-color: @transparent;
    size:             1.2em;
}}

element-text {{
    background-color: @transparent;
    text-color:       inherit;
    vertical-align:   0.5;
}}
"""

    if dry_run:
        changes.append({"app": "rofi", "action": "dry-run", "path": str(theme_path)})
        return changes

    rofi_dir.mkdir(parents=True, exist_ok=True)
    theme_backup = backup_file(theme_path, backup_ts, "rofi/hermes-theme.rasi")
    config_backup = backup_file(config_path, backup_ts, "rofi/config.rasi")
    theme_path.write_text(content, encoding="utf-8")
    changes.append({"app": "rofi", "action": "write", "path": str(theme_path), "backup": theme_backup})

    theme_ref = f'@theme "{theme_path}"'
    hermes_marker = "/* linux-ricing */"
    injected = False
    if config_path.exists():
        conf_text = config_path.read_text(encoding="utf-8")
        if str(theme_path) not in conf_text:
            config_path.write_text(conf_text + f"\n{hermes_marker}\n{theme_ref}\n", encoding="utf-8")
            injected = True
    else:
        config_path.write_text(f"{hermes_marker}\n{theme_ref}\n", encoding="utf-8")
        injected = True

    changes.append({"app": "rofi", "action": "inject_theme", "path": str(config_path),
                    "backup": config_backup, "injected": injected,
                    "theme_ref": theme_ref, "marker": hermes_marker})
    return changes


# ---------------------------------------------------------------------------
# Wofi
# ---------------------------------------------------------------------------

def materialize_wofi(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    wofi_dir = HOME / ".config" / "wofi"
    style_path = wofi_dir / "style.css"
    template_path = TEMPLATES_DIR / "wofi" / "style.css.template"
    changes = []

    if not template_path.exists():
        print(f"[wofi] template not found, skipping: {template_path}", file=sys.stderr)
        return changes

    mood_tags = design.get("mood_tags", [])
    radius = "0px" if any(t in mood_tags for t in ["gothic", "game", "angular", "sharp"]) else "8px"
    selected_text = yiq_text_color(palette["primary"])
    context = {**palette, "name": design.get("name", "theme"),
               "radius": radius, "selected_text": selected_text}
    content = render_template(template_path, context)

    if dry_run:
        changes.append({"app": "wofi", "action": "dry-run", "path": str(style_path)})
        return changes

    wofi_dir.mkdir(parents=True, exist_ok=True)
    style_backup = backup_file(style_path, backup_ts, "wofi/style.css")
    style_path.write_text(content, encoding="utf-8")
    changes.append({"app": "wofi", "action": "write", "path": str(style_path), "backup": style_backup})
    return changes
