"""Notification daemon materializers: Dunst, Mako, SwayNC."""
import sys

from core.constants import HOME, TEMPLATES_DIR
from core.colors import yiq_text_color
from core.process import run_cmd
from core.backup import backup_file
from core.templates import render_template


# ---------------------------------------------------------------------------
# Dunst
# ---------------------------------------------------------------------------

def materialize_dunst(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    dunst_dir = HOME / ".config" / "dunst"
    dunstrc = dunst_dir / "dunstrc"
    fragment_path = dunst_dir / "hermes-dunstrc"
    changes = []

    fragment_content = f"""# Generated by linux-ricing — {design.get('name', 'theme')}
# Include this in dunstrc with: include = ~/.config/dunst/hermes-dunstrc
# (dunst >= 1.7.0 supports include directives)

[global]
    frame_color = {palette['primary']}
    separator_color = {palette['surface']}

[urgency_low]
    background = {palette['background']}
    foreground = {palette['muted']}
    frame_color = {palette['surface']}

[urgency_normal]
    background = {palette['background']}
    foreground = {palette['foreground']}
    frame_color = {palette['primary']}

[urgency_critical]
    background = {palette['danger']}
    foreground = {palette['background']}
    frame_color = {palette['danger']}
"""

    if dry_run:
        changes.append({"app": "dunst", "action": "dry-run", "path": str(fragment_path)})
        return changes

    dunst_dir.mkdir(parents=True, exist_ok=True)
    fragment_backup = backup_file(fragment_path, backup_ts, "dunst/hermes-dunstrc")
    dunstrc_backup = backup_file(dunstrc, backup_ts, "dunst/dunstrc")
    fragment_path.write_text(fragment_content, encoding="utf-8")
    changes.append({"app": "dunst", "action": "write", "path": str(fragment_path), "backup": fragment_backup})

    include_line = f"include = {fragment_path}"
    hermes_marker = "# linux-ricing"
    hermes_marker_end = "# end-linux-ricing"
    injected = False
    if dunstrc.exists():
        dunstrc_text = dunstrc.read_text(encoding="utf-8")
        if str(fragment_path) not in dunstrc_text:
            if "[global]" in dunstrc_text:
                dunstrc_text = dunstrc_text.replace(
                    "[global]",
                    f"{hermes_marker}\n{include_line}\n{hermes_marker_end}\n\n[global]",
                    1,
                )
            else:
                dunstrc_text += f"\n{hermes_marker}\n{include_line}\n{hermes_marker_end}\n"
            dunstrc.write_text(dunstrc_text, encoding="utf-8")
            injected = True

    changes.append({"app": "dunst", "action": "inject_include", "path": str(dunstrc),
                    "backup": dunstrc_backup, "injected": injected,
                    "include_line": include_line,
                    "marker": hermes_marker, "marker_end": hermes_marker_end})
    run_cmd(["pkill", "-USR1", "dunst"], timeout=3)
    return changes


# ---------------------------------------------------------------------------
# Mako
# ---------------------------------------------------------------------------

def materialize_mako(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    mako_dir = HOME / ".config" / "mako"
    config_path = mako_dir / "config"
    template_path = TEMPLATES_DIR / "mako" / "config.template"
    changes = []

    if not template_path.exists():
        print(f"[mako] template not found, skipping: {template_path}", file=sys.stderr)
        return changes

    mood_tags = design.get("mood_tags", [])
    corner_radius = 0 if any(t in mood_tags for t in ["gothic", "game", "angular", "sharp"]) else 8
    context = {**palette, "name": design.get("name", "theme"), "corner_radius": corner_radius}
    content = render_template(template_path, context)

    if dry_run:
        changes.append({"app": "mako", "action": "dry-run", "path": str(config_path)})
        return changes

    mako_dir.mkdir(parents=True, exist_ok=True)
    config_backup = backup_file(config_path, backup_ts, "mako/config")
    config_path.write_text(content, encoding="utf-8")
    changes.append({"app": "mako", "action": "write", "path": str(config_path), "backup": config_backup})
    run_cmd(["makoctl", "reload"], timeout=3)
    return changes


# ---------------------------------------------------------------------------
# SwayNC
# ---------------------------------------------------------------------------

def materialize_swaync(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    swaync_dir = HOME / ".config" / "swaync"
    style_path = swaync_dir / "style.css"
    template_path = TEMPLATES_DIR / "swaync" / "style.css.template"
    changes = []

    if not template_path.exists():
        print(f"[swaync] template not found, skipping: {template_path}", file=sys.stderr)
        return changes

    mood_tags = design.get("mood_tags", [])
    radius = "0px" if any(t in mood_tags for t in ["gothic", "game", "angular", "sharp"]) else "8px"
    selected_text = yiq_text_color(palette["primary"])
    danger_text = yiq_text_color(palette["danger"])
    context = {**palette, "name": design.get("name", "theme"),
               "radius": radius, "selected_text": selected_text, "danger_text": danger_text}
    content = render_template(template_path, context)

    if dry_run:
        changes.append({"app": "swaync", "action": "dry-run", "path": str(style_path)})
        return changes

    swaync_dir.mkdir(parents=True, exist_ok=True)
    style_backup = backup_file(style_path, backup_ts, "swaync/style.css")
    style_path.write_text(content, encoding="utf-8")
    changes.append({"app": "swaync", "action": "write", "path": str(style_path), "backup": style_backup})
    run_cmd(["swaync-client", "--reload-css"], timeout=3)
    return changes
