"""System-level materializers: GTK, Picom, Fastfetch, Starship prompt."""
import json
import re
import sys

from core.constants import HOME, TEMPLATES_DIR
from core.colors import is_dark_palette, yiq_text_color, adjust_lightness
from core.process import run_cmd, cmd_exists
from core.backup import backup_file
from core.templates import render_template


# ---------------------------------------------------------------------------
# GTK
# ---------------------------------------------------------------------------

def _build_gtk_css(design: dict) -> str:
    """Build GTK 3/4 CSS color overrides from the active palette."""
    p = design.get("palette", {})
    name = design.get("name", "theme")
    background = p.get("background", "#1e1e2e")
    foreground = p.get("foreground", "#cdd6f4")
    primary = p.get("primary", "#89b4fa")
    surface = p.get("surface", "#313244")
    muted = p.get("muted", "#6c7086")
    danger = p.get("danger", "#f38ba8")
    success = p.get("success", "#a6e3a1")
    warning = p.get("warning", "#f9e2af")

    return f"""/* Generated by linux-ricing — {name} */
@define-color accent_color {primary};
@define-color accent_bg_color {primary};
@define-color accent_fg_color {background};
@define-color destructive_color {danger};
@define-color success_color {success};
@define-color warning_color {warning};
@define-color error_color {danger};

window {{
  background-color: {background};
  color: {foreground};
}}

headerbar {{
  background-color: {surface};
  color: {foreground};
  border-bottom: 1px solid {primary};
}}

entry {{
  background-color: {surface};
  color: {foreground};
  border: 1px solid {muted};
}}

entry:focus {{
  border-color: {primary};
}}

button {{
  background-color: {surface};
  color: {foreground};
}}

button:hover {{
  background-color: {primary};
  color: {background};
}}
"""


def materialize_gtk(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    """Apply GTK theme, icon theme, cursor theme, and CSS overrides."""
    palette = design["palette"]
    template_path = TEMPLATES_DIR / "gtk" / "settings.ini.template"
    changes = []

    is_dark = is_dark_palette(palette)
    gtk_theme    = design.get("gtk_theme",    "Adwaita-dark" if is_dark else "Adwaita")
    icon_theme   = design.get("icon_theme",   "Papirus-Dark" if is_dark else "Papirus")
    cursor_theme = design.get("cursor_theme", "default")

    ui_font = design.get("typography", {}).get("ui_font", "JetBrains Mono")
    context = {
        **palette,
        "name": design.get("name", "theme"),
        "gtk_theme": gtk_theme,
        "icon_theme": icon_theme,
        "cursor_theme": cursor_theme,
        "font_name": f"{ui_font} 10",
        "prefer_dark": "1" if is_dark else "0",
    }
    settings_content = render_template(template_path, context)
    css_content = _build_gtk_css(design)

    if dry_run:
        changes.append({"app": "gtk", "action": "dry-run", "gtk_theme": gtk_theme,
                        "icon_theme": icon_theme, "cursor_theme": cursor_theme, "dark": is_dark,
                        "gtk3_css": str(HOME / ".config" / "gtk-3.0" / "gtk.css"),
                        "gtk4_css": str(HOME / ".config" / "gtk-4.0" / "gtk.css")})
        return changes

    for gtk_dir_name in ["gtk-3.0", "gtk-4.0"]:
        gtk_dir = HOME / ".config" / gtk_dir_name
        gtk_dir.mkdir(parents=True, exist_ok=True)
        settings_path = gtk_dir / "settings.ini"
        backup = backup_file(settings_path, backup_ts, f"gtk/{gtk_dir_name}/settings.ini")
        settings_path.write_text(settings_content, encoding="utf-8")
        changes.append({"app": "gtk", "action": "write", "path": str(settings_path), "backup": backup})

        css_path = gtk_dir / "gtk.css"
        css_backup = backup_file(css_path, backup_ts, f"gtk/{gtk_dir_name}/gtk.css")
        css_path.write_text(css_content, encoding="utf-8")
        changes.append({"app": "gtk", "action": "write", "path": str(css_path), "backup": css_backup})

    if cmd_exists("gsettings"):
        schema = "org.gnome.desktop.interface"
        for key, val in [("gtk-theme", gtk_theme), ("icon-theme", icon_theme), ("cursor-theme", cursor_theme)]:
            rc, _, _ = run_cmd(["gsettings", "set", schema, key, val])
            changes.append({"app": "gtk", "action": "gsettings", "key": key, "value": val, "success": rc == 0})

    # Expose GTK config dirs so Flatpak apps read our settings.ini (--user, no sudo).
    if cmd_exists("flatpak") and design.get("apply_flatpak_overrides", True):
        flatpak_overrides = [
            ["--filesystem", "xdg-config/gtk-3.0:ro"],
            ["--filesystem", "xdg-config/gtk-4.0:ro"],
            ["--filesystem", "xdg-data/icons:ro"],
        ]
        ok = True
        for args in flatpak_overrides:
            rc, _, _ = run_cmd(["flatpak", "override", "--user"] + args, timeout=10)
            if rc != 0:
                ok = False
        changes.append({"app": "gtk", "action": "flatpak-override",
                        "gtk_theme": gtk_theme, "icon_theme": icon_theme, "success": ok})

    return changes


# ---------------------------------------------------------------------------
# Picom
# ---------------------------------------------------------------------------

def materialize_picom(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    """Write a picom theme fragment and @include it into picom.conf."""
    palette = design["palette"]
    picom_dir = HOME / ".config" / "picom"
    picom_conf = picom_dir / "picom.conf"
    fragment_path = picom_dir / "hermes-picom.conf"
    template_path = TEMPLATES_DIR / "picom" / "hermes-picom.conf.template"
    changes = []

    if not template_path.exists():
        print(f"[picom] template not found, skipping: {template_path}", file=sys.stderr)
        return changes

    shadow_color = adjust_lightness(palette["primary"], 0.25)
    context = {**palette, "name": design.get("name", "theme"), "shadow_color": shadow_color}
    fragment_content = render_template(template_path, context)

    if dry_run:
        changes.append({"app": "picom", "action": "dry-run", "path": str(fragment_path)})
        return changes

    picom_dir.mkdir(parents=True, exist_ok=True)
    fragment_backup = backup_file(fragment_path, backup_ts, "picom/hermes-picom.conf")
    picom_backup = backup_file(picom_conf, backup_ts, "picom/picom.conf")
    fragment_path.write_text(fragment_content, encoding="utf-8")
    changes.append({"app": "picom", "action": "write", "path": str(fragment_path), "backup": fragment_backup})

    hermes_marker = "# linux-ricing"
    include_line = f'@include "{fragment_path}";'
    injected = False
    if picom_conf.exists():
        picom_text = picom_conf.read_text(encoding="utf-8")
        if "hermes-picom.conf" not in picom_text:
            picom_conf.write_text(f"{hermes_marker}\n{include_line}\n\n" + picom_text, encoding="utf-8")
            injected = True
    else:
        picom_conf.write_text(
            f"{hermes_marker}\n{include_line}\n\n"
            "# Hermes wrote this starter config. Add your own settings below:\n"
            'backend = "glx";\nvsync = true;\n',
            encoding="utf-8"
        )
        injected = True

    changes.append({"app": "picom", "action": "inject_include", "path": str(picom_conf),
                    "backup": picom_backup, "injected": injected, "marker": hermes_marker})
    run_cmd(["pkill", "-HUP", "picom"], timeout=3)
    return changes


# ---------------------------------------------------------------------------
# Fastfetch
# ---------------------------------------------------------------------------

def materialize_fastfetch(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    """Rewrite ~/.config/fastfetch/config.jsonc with palette-derived colors.

    Writes to ``config.jsonc`` (fastfetch's preferred and only auto-loaded
    filename); a legacy ``config.json`` left from older runs is moved to
    backup so it does not confuse future maintenance.
    """
    palette = design["palette"]
    mood_tags = design.get("mood_tags", [])
    name = design.get("name", "theme")
    fastfetch_dir = HOME / ".config" / "fastfetch"
    config_path = fastfetch_dir / "config.jsonc"
    legacy_json_path = fastfetch_dir / "config.json"
    changes = []

    if any(t in mood_tags for t in ["gothic", "blood", "fantasy", "dark-fantasy"]):
        separator = " ♦ "
    elif any(t in mood_tags for t in ["game", "rpg", "maplestory", "pixel"]):
        separator = " ♥ "
    elif any(t in mood_tags for t in ["void", "dragon", "cyber", "neon"]):
        separator = " 𑁍 "
    else:
        separator = " ─ "

    # Fastfetch 2.x requires the leading '#' on hex color values; without it
    # the binary aborts with "invalid color code found: <bare-hex>".
    config = {
        "logo":    {"type": "auto", "color": {"1": palette["primary"], "2": palette["accent"]}},
        "display": {"separator": separator, "color": {
            "title": palette["primary"],
            "keys":  palette["accent"],
            "separator": palette["warning"],
        }},
        "modules": [
            {"type": "title",    "key": f"  {name.upper()}",  "keyColor": palette["primary"]},
            {"type": "separator","string": "─"},
            {"type": "os",       "key": "  OS",     "keyColor": palette["primary"]},
            {"type": "kernel",   "key": "  Kernel", "keyColor": palette["accent"]},
            {"type": "uptime",   "key": "  Uptime", "keyColor": palette["success"]},
            {"type": "de",       "key": "  WM",     "keyColor": palette["secondary"]},
            {"type": "terminal", "key": "  Term",   "keyColor": palette["primary"]},
            {"type": "shell",    "key": "  Shell",  "keyColor": palette["accent"]},
            {"type": "cpu",      "key": "  CPU",    "keyColor": palette["warning"]},
            {"type": "memory",   "key": "  RAM",    "keyColor": palette["danger"]},
            {"type": "colors",   "paddingLeft": 2,  "symbol": "circle"},
        ],
    }

    if dry_run:
        changes.append({"app": "fastfetch", "action": "dry-run", "path": str(config_path)})
        return changes

    fastfetch_dir.mkdir(parents=True, exist_ok=True)
    config_backup = backup_file(config_path, backup_ts, "fastfetch/config.jsonc")
    config_path.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")
    changes.append({"app": "fastfetch", "action": "write", "path": str(config_path), "backup": config_backup})

    # Retire any legacy config.json so future inspectors don't confuse it
    # with the active config.jsonc that fastfetch actually loads.
    if legacy_json_path.exists():
        legacy_backup = backup_file(legacy_json_path, backup_ts, "fastfetch/config.json")
        legacy_json_path.unlink()
        changes.append({"app": "fastfetch", "action": "retire-legacy",
                        "path": str(legacy_json_path), "backup": legacy_backup})
    return changes


# ---------------------------------------------------------------------------
# Starship prompt
# ---------------------------------------------------------------------------

def materialize_starship(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    """Write ~/.config/starship.toml with palette-derived colors."""
    palette = design["palette"]
    raw_name = design.get("name", "rice")
    theme_name = re.sub(r"[^a-zA-Z0-9-]+", "-", raw_name).strip("-") or "rice"
    config_path = HOME / ".config" / "starship.toml"
    changes = []

    content = _build_starship_toml(palette, theme_name)

    if dry_run:
        changes.append({"app": "starship", "action": "dry-run", "path": str(config_path)})
        return changes

    config_backup = backup_file(config_path, backup_ts, "starship/starship.toml")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(content, encoding="utf-8")
    changes.append({"app": "starship", "action": "write", "path": str(config_path), "backup": config_backup})
    return changes


def _build_starship_toml(palette: dict, theme_name: str) -> str:
    """Build a starship.toml using the [palettes.*] feature for named color slots."""
    p = palette
    lines = [
        f'palette = "{theme_name}"',
        "",
        f"[palettes.{theme_name}]",
        f'background = "{p["background"]}"',
        f'foreground = "{p["foreground"]}"',
        f'primary    = "{p["primary"]}"',
        f'secondary  = "{p["secondary"]}"',
        f'accent     = "{p["accent"]}"',
        f'surface    = "{p["surface"]}"',
        f'muted      = "{p["muted"]}"',
        f'danger     = "{p["danger"]}"',
        f'success    = "{p["success"]}"',
        f'warning    = "{p["warning"]}"',
        "",
        "[character]",
        'success_symbol = "[❯](bold success)"',
        'error_symbol   = "[❯](bold danger)"',
        "",
        "[directory]",
        'style = "bold primary"',
        "",
        "[git_branch]",
        'style = "bold secondary"',
        "",
        "[git_status]",
        'style = "bold warning"',
        "",
        "[cmd_duration]",
        'style       = "bold muted"',
        "min_time    = 2000",
        "",
        "[username]",
        'style_user = "bold accent"',
        'style_root = "bold danger"',
        "show_always = false",
        "",
        "[hostname]",
        'style    = "bold accent"',
        "ssh_only = true",
        "",
    ]
    return "\n".join(lines)
