"""Terminal emulator materializers: kitty, Alacritty, Konsole."""
from pathlib import Path

from core.constants import HOME, TEMPLATES_DIR
from core.colors import (
    hex_to_rgb, adjust_lightness, rotate_hue, yiq_text_color,
)
from core.process import run_cmd, cmd_exists, _get_kwrite
from core.backup import backup_file
from core.templates import jinja2, simple_render, render_template
from core.snapshots import snapshot_konsole_state
from materializers.terminal_colors import build_konsole_colorscheme


# ---------------------------------------------------------------------------
# kitty
# ---------------------------------------------------------------------------

def materialize_kitty(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    kitty_dir = HOME / ".config" / "kitty"
    theme_path = kitty_dir / "theme.conf"
    main_config = kitty_dir / "kitty.conf"
    changes = []

    blue_slot = palette['secondary'] if palette['primary'] == palette['warning'] else palette['primary']
    blue_bright = adjust_lightness(rotate_hue(blue_slot, -10), 1.3)

    content = f"""# Generated by linux-ricing — {design.get('name', 'theme')}
background {palette['background']}
foreground {palette['foreground']}
cursor {palette['accent']}
cursor_text_color {yiq_text_color(palette['accent'])}
selection_background {palette['primary']}
selection_foreground {yiq_text_color(palette['primary'])}
# --- ANSI normal (0-7) ---
color0 {palette['surface']}
color1 {palette['danger']}
color2 {palette['success']}
color3 {palette['warning']}
color4 {blue_slot}
color5 {palette['secondary']}
color6 {palette['accent']}
color7 {palette['foreground']}
# --- ANSI bright/intense (8-15): hue-rotated and lightened for variety ---
color8  {adjust_lightness(palette['muted'], 1.4)}
color9  {adjust_lightness(rotate_hue(palette['danger'], 15), 1.3)}
color10 {adjust_lightness(rotate_hue(palette['success'], 10), 1.3)}
color11 {adjust_lightness(palette['warning'], 1.3)}
color12 {blue_bright}
color13 {adjust_lightness(rotate_hue(palette['secondary'], 20), 1.3)}
color14 {adjust_lightness(rotate_hue(palette['accent'], 15), 1.3)}
color15 {adjust_lightness(palette['foreground'], 1.25)}
"""

    if dry_run:
        changes.append({"app": "kitty", "action": "dry-run", "path": str(theme_path)})
        return changes

    kitty_dir.mkdir(parents=True, exist_ok=True)
    theme_backup = backup_file(theme_path, backup_ts, "kitty/theme.conf")
    main_backup = backup_file(main_config, backup_ts, "kitty/kitty.conf")
    theme_path.write_text(content, encoding="utf-8")
    changes.append({"app": "kitty", "action": "write", "path": str(theme_path), "backup": theme_backup})

    include_line = "include theme.conf"
    hermes_marker = "# linux-ricing"
    if main_config.exists():
        cleaned = []
        for ln in main_config.read_text(encoding="utf-8").splitlines():
            if ln.strip() == include_line:
                if cleaned and cleaned[-1].strip() == hermes_marker:
                    cleaned.pop()
                continue
            cleaned.append(ln)
        new_text = "\n".join(cleaned).rstrip() + f"\n\n{hermes_marker}\n{include_line}\n"
        main_config.write_text(new_text, encoding="utf-8")
    else:
        main_config.write_text(f"{hermes_marker}\n{include_line}\n", encoding="utf-8")
    include_injected = True

    changes.append({"app": "kitty", "action": "inject_include", "path": str(main_config),
                    "backup": main_backup, "injected": include_injected,
                    "include_line": include_line, "marker": hermes_marker})
    return changes


# ---------------------------------------------------------------------------
# Konsole
# ---------------------------------------------------------------------------

def materialize_konsole(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    palette = design["palette"]
    konsole_dir = HOME / ".local" / "share" / "konsole"
    profile_name = "linux-ricing"
    profile_path = konsole_dir / f"{profile_name}.profile"
    color_scheme_name = f"hermes-{design.get('name', 'ricer')}"
    color_scheme_path = konsole_dir / f"{color_scheme_name}.colorscheme"
    konsolerc = HOME / ".config" / "konsolerc"
    changes = []

    p = {k: hex_to_rgb(v) for k, v in palette.items()}
    blue_hex = palette['secondary'] if palette['primary'] == palette['warning'] else palette['primary']
    p['blue'] = hex_to_rgb(blue_hex)
    pi = {
        "muted":      hex_to_rgb(adjust_lightness(palette["muted"], 1.4)),
        "danger":     hex_to_rgb(adjust_lightness(rotate_hue(palette["danger"], 15), 1.3)),
        "success":    hex_to_rgb(adjust_lightness(rotate_hue(palette["success"], 10), 1.3)),
        "warning":    hex_to_rgb(adjust_lightness(palette["warning"], 1.3)),
        "blue":       hex_to_rgb(adjust_lightness(rotate_hue(blue_hex, -10), 1.3)),
        "secondary":  hex_to_rgb(adjust_lightness(rotate_hue(palette["secondary"], 20), 1.3)),
        "accent":     hex_to_rgb(adjust_lightness(rotate_hue(palette["accent"], 15), 1.3)),
        "foreground": hex_to_rgb(adjust_lightness(palette["foreground"], 1.25)),
    }
    color_scheme_content = build_konsole_colorscheme(p, pi, color_scheme_name)
    cursor_rgb = hex_to_rgb(palette["accent"])
    cursor_text_rgb = hex_to_rgb(yiq_text_color(palette["accent"]))
    profile_content = f"""[Appearance]
ColorScheme={color_scheme_name}

[Cursor Options]
CustomCursorColor={cursor_rgb}
CustomCursorTextColor={cursor_text_rgb}
UseCustomCursorColor=true

[General]
Name={profile_name}
Parent=FALLBACK/
"""

    if dry_run:
        state = snapshot_konsole_state()
        changes.append({"app": "konsole", "action": "dry-run", "profile_path": str(profile_path),
                        "previous_profile": state["default_profile"]})
        return changes

    state = snapshot_konsole_state()
    prev_profile = state["default_profile"]
    profile_backup = backup_file(profile_path, backup_ts, f"konsole/{profile_name}.profile")
    colors_backup = backup_file(color_scheme_path, backup_ts, f"konsole/{color_scheme_name}.colorscheme")
    konsolerc_backup = backup_file(konsolerc, backup_ts, "konsole/konsolerc")

    konsole_dir.mkdir(parents=True, exist_ok=True)
    color_scheme_path.write_text(color_scheme_content, encoding="utf-8")
    profile_path.write_text(profile_content, encoding="utf-8")

    kwrite = _get_kwrite()
    if kwrite:
        run_cmd([kwrite, "--file", "konsolerc", "--group", "Desktop Entry",
                 "--key", "DefaultProfile", f"{profile_name}.profile"])

    changes.append({"app": "konsole", "action": "write",
                    "profile_path": str(profile_path), "color_scheme_path": str(color_scheme_path),
                    "backup_profile": profile_backup, "backup_colors": colors_backup,
                    "backup_konsolerc": konsolerc_backup, "previous_profile": prev_profile})
    return changes


# ---------------------------------------------------------------------------
# Alacritty
# ---------------------------------------------------------------------------

def materialize_alacritty(design: dict, backup_ts: str, dry_run: bool = False) -> list[dict]:
    """Write colors.toml and inject import into alacritty.toml."""
    palette = design["palette"]
    alacritty_dir = HOME / ".config" / "alacritty"
    template_path = TEMPLATES_DIR / "alacritty" / "colors.toml.template"
    colors_path = alacritty_dir / "colors.toml"
    toml_config = alacritty_dir / "alacritty.toml"
    changes = []

    context = {**palette, "name": design.get("name", "theme")}

    if template_path.exists():
        bright_map = {
            "{{muted}}":      adjust_lightness(palette["muted"], 1.4),
            "{{danger}}":     adjust_lightness(rotate_hue(palette["danger"], 15), 1.3),
            "{{success}}":    adjust_lightness(rotate_hue(palette["success"], 10), 1.3),
            "{{warning}}":    adjust_lightness(palette["warning"], 1.3),
            "{{primary}}":    adjust_lightness(rotate_hue(palette["primary"], -10), 1.3),
            "{{secondary}}":  adjust_lightness(rotate_hue(palette["secondary"], 20), 1.3),
            "{{accent}}":     adjust_lightness(rotate_hue(palette["accent"], 15), 1.3),
            "{{foreground}}": adjust_lightness(palette["foreground"], 1.25),
        }
        template_str = template_path.read_text(encoding="utf-8")
        bright_start = template_str.find("[colors.bright]")
        if bright_start != -1:
            bright_section = template_str[bright_start:]
            for k, v in bright_map.items():
                bright_section = bright_section.replace(k, v, 1)
            template_str = template_str[:bright_start] + bright_section
        if jinja2:
            env = jinja2.Environment(undefined=jinja2.StrictUndefined)
            content = env.from_string(template_str).render(**context)
        else:
            content = simple_render(template_str, context)
    else:
        content = (
            f'# Generated by linux-ricing — {design.get("name", "theme")}\n'
            f'[colors.primary]\nbackground = "{palette["background"]}"\nforeground = "{palette["foreground"]}"\n\n'
            f'[colors.cursor]\ntext   = "{palette["background"]}"\ncursor = "{palette["accent"]}"\n\n'
            f'[colors.selection]\ntext       = "{palette["background"]}"\nbackground = "{palette["primary"]}"\n\n'
            f'[colors.normal]\n'
            f'black   = "{palette["surface"]}"\nred     = "{palette["danger"]}"\n'
            f'green   = "{palette["success"]}"\nyellow  = "{palette["warning"]}"\n'
            f'blue    = "{palette["primary"]}"\nmagenta = "{palette["secondary"]}"\n'
            f'cyan    = "{palette["accent"]}"\nwhite   = "{palette["foreground"]}"\n\n'
            f'[colors.bright]\n'
            f'black   = "{adjust_lightness(palette["muted"], 1.4)}"\n'
            f'red     = "{adjust_lightness(rotate_hue(palette["danger"], 15), 1.3)}"\n'
            f'green   = "{adjust_lightness(rotate_hue(palette["success"], 10), 1.3)}"\n'
            f'yellow  = "{adjust_lightness(palette["warning"], 1.3)}"\n'
            f'blue    = "{adjust_lightness(rotate_hue(palette["primary"], -10), 1.3)}"\n'
            f'magenta = "{adjust_lightness(rotate_hue(palette["secondary"], 20), 1.3)}"\n'
            f'cyan    = "{adjust_lightness(rotate_hue(palette["accent"], 15), 1.3)}"\n'
            f'white   = "{adjust_lightness(palette["foreground"], 1.25)}"\n'
        )

    if dry_run:
        changes.append({"app": "alacritty", "action": "dry-run", "path": str(colors_path)})
        return changes

    alacritty_dir.mkdir(parents=True, exist_ok=True)
    colors_backup = backup_file(colors_path, backup_ts, "alacritty/colors.toml")
    toml_backup = backup_file(toml_config, backup_ts, "alacritty/alacritty.toml")
    colors_path.write_text(content, encoding="utf-8")
    changes.append({"app": "alacritty", "action": "write", "path": str(colors_path), "backup": colors_backup})

    import_line = 'import = ["~/.config/alacritty/colors.toml"]'
    hermes_marker = "# linux-ricing"
    injected = False
    if toml_config.exists():
        toml_text = toml_config.read_text(encoding="utf-8")
        if "colors.toml" not in toml_text:
            toml_config.write_text(f"{hermes_marker}\n{import_line}\n\n" + toml_text, encoding="utf-8")
            injected = True
    else:
        toml_config.write_text(f"{hermes_marker}\n{import_line}\n", encoding="utf-8")
        injected = True

    changes.append({"app": "alacritty", "action": "inject_import", "path": str(toml_config),
                    "backup": toml_backup, "injected": injected, "marker": hermes_marker})
    return changes

