#!/usr/bin/env bash
# =============================================================================
# linux-ricing setup script
# Creates a project-local venv (via uv or python3 -m venv), installs Python
# deps into it, and writes a wrapper script to ~/.local/bin/ricer that
# always invokes the venv interpreter — no system Python pollution.
# Run once after cloning, and again after pulling updates.
# =============================================================================
set -euo pipefail

# ── Platform guard ──────────────────────────────────────────────────────────
if [[ "$(uname -s)" != "Linux" ]]; then
    echo "ERROR: linux-ricing requires a Linux desktop environment." >&2
    echo "Detected platform: $(uname -s)" >&2
    echo "" >&2
    echo "This skill customises Linux window managers (KDE Plasma, GNOME," >&2
    echo "Hyprland) and depends on Linux-specific tools and config paths." >&2
    echo "It cannot run on $(uname -s)." >&2
    exit 1
fi

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RICER_PY="$SKILL_DIR/scripts/ricer.py"
REQUIREMENTS="$SKILL_DIR/requirements.txt"
VENV_DIR="$SKILL_DIR/.venv"
CACHE_DIR="$HOME/.cache/linux-ricing"
LOCAL_BIN="$HOME/.local/bin"
WRAPPER="$LOCAL_BIN/ricer"

echo "=== linux-ricing setup ==="
echo "Skill dir : $SKILL_DIR"
echo "Venv      : $VENV_DIR"
echo ""

# --- 1. Virtual environment + Python deps ---
echo "[1/4] Setting up Python virtual environment..."

if command -v uv &>/dev/null; then
    echo "  Tool     : uv $(uv --version 2>&1 | head -1)"
    uv venv --quiet --clear "$VENV_DIR"
    uv pip install --quiet --python "$VENV_DIR" -r "$REQUIREMENTS"
else
    echo "  uv not found — falling back to python3 -m venv + pip"
    echo "  (Install uv for faster setup: https://astral.sh/uv)"
    python3 -m venv "$VENV_DIR"
    "$VENV_DIR/bin/pip" install --quiet -r "$REQUIREMENTS"
fi

echo "  Packages : $(paste -sd ' ' "$REQUIREMENTS")"
echo "  Venv     : OK"

# --- 2. Make ricer.py executable ---
echo ""
echo "[2/4] Setting permissions..."
chmod +x "$RICER_PY"
echo "  ricer.py : chmod +x done"

# --- 3. Create cache dirs ---
echo ""
echo "[3/4] Creating cache directories..."
mkdir -p "$CACHE_DIR/backups"
mkdir -p "$CACHE_DIR/current/history"
echo "  $CACHE_DIR : created"

# --- 4. Write wrapper script into ~/.local/bin ---
echo ""
echo "[4/4] Writing ricer wrapper -> $WRAPPER..."
mkdir -p "$LOCAL_BIN"

# Remove any old symlink first so we write a real file, not follow the link.
if [ -L "$WRAPPER" ]; then
    rm -f "$WRAPPER"
fi

# Write (or overwrite) a small wrapper that calls the venv Python directly.
# Using a wrapper rather than a symlink means the venv is always used,
# even if the user's active python3 differs.
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by linux-ricing/scripts/setup.sh — re-run setup to update.
exec "$VENV_DIR/bin/python3" "$RICER_PY" "\$@"
EOF
chmod +x "$WRAPPER"
echo "  wrapper  : $WRAPPER"

# --- PATH check ---
if [[ ":$PATH:" != *":$LOCAL_BIN:"* ]]; then
    echo ""
    echo "  WARNING: $LOCAL_BIN is not in your PATH."
    echo "  Add this to ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# --- Smoke test ---
echo ""
echo "=== Smoke test ==="
if "$WRAPPER" status 2>/dev/null; then
    echo ""
    echo "Setup complete. Run 'ricer --help' to get started."
else
    echo ""
    echo "Setup complete. Run directly:"
    echo "  $WRAPPER --help"
fi
